import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)
plt.figure()
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.title('Plot of y = sin(x)')

x = np.arange(0, 10.1, 0.1)
y1 = np.sin(x)
plt.figure()
plt.plot(x, y1)

y2 = np.sin(np.arange(0, 10.1, 0.1))
plt.figure()
plt.plot(y2)

x = np.arange(0, 10.1, 0.1)
y1 = np.sin(x)
y2 = np.cos(x)
plt.figure()
plt.plot(x, y1, x, y2)
plt.legend(['sin(x)', 'cos(x)'])

x = np.linspace(0, 2 * np.pi, 100)
y = np.cos(x)
plt.figure()
plt.plot(x, y, 'r--o')
plt.xlabel('x')
plt.ylabel('cos(x)')
plt.title('Plot of y = cos(x) with custom style')

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)
plt.figure()
plt.plot(x, y)
plt.title('Saving Figure Example')
plt.savefig('sine_plot_savefig.png', dpi=300)

x = np.linspace(0, 2 * np.pi, 100)
y1 = np.sin(x)
y2 = np.cos(x)
plt.figure()
plt.plot(x, y1, 'b-', x, y2, 'r--')
plt.legend(['sin(x)', 'cos(x)'])
plt.xlabel('x')
plt.ylabel('y')
plt.title('Multiple Functions on Same Axes')
plt.grid(True)
plt.axis([0, 2 * np.pi, -1.5, 1.5])
plt.show()
